### ISSUE TITLE
Depthwise separable convolution incomplete?

### ISSUE THREAD

**Issue by TobiasB22** [EscVM/Efficient-CapsNet#10]
Hi @EscVM,

to me, it seems like the depth wise separable convolution implemented in https://github.com/EscVM/Efficient-CapsNet/blob/705449c/utils/layers.py#L123 lacks the point-wise convolution part?! 

Shouldn't there be a second Conv2D layer with F filters of kernel size (1,1)?

Otherwise, you're doing a simple depth-wise convolution, right?

I am referencing https://towardsdatascience.com/a-basic-introduction-to-separable-convolutions-b99ec3102728 here btw. 
Not sure if you gave a reference for the depthwise separable convolution in your paper.

**Comment by EscVM** [comment]
Hi @TobiasB22,

Yes, you are right! As specified in the pre-print paper version, no point-wise convolution operation is needed to construct the primary capsule layer.

**Comment by TobiasB22** [comment]
Ok, thanks! I guess I must've skipped that part while reading the paper.
