### ISSUE TITLE
Performance issues in utils/pre_process_mnist.py(P2)

### ISSUE THREAD

**Issue by DLPerf** [EscVM/Efficient-CapsNet#11]
Hello,I found a performance issue in the definition of `generate_tf_data` ,
utils/pre_process_mnist.py,
[dataset_train = dataset_train.map](https://github.com/EscVM/Efficient-CapsNet/blob/3d8d51e7a7c777c59eb8db9dae8bb14d72d5de03/utils/pre_process_mnist.py#L116) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by EscVM** [comment]
Hi @DLPerf!

Yes, you are perfectly right. I'm gonna change asap.

Thanks,

V.M.
