### ISSUE TITLE
UnimplementedError: Fused conv implementation does not support grouped convolutions for now

### ISSUE THREAD

**Issue by MFalam** [EscVM/Efficient-CapsNet#14]
Thanks for sharing the code of your awesome work.

I am trying to run the different .ipynb of your work. However,  once I run the "1.2.1 Evaluate the model" 

`model_test.evaluate(mnist_dataset.X_test, mnist_dataset.y_test)`

I get the following error:

`UnimplementedError:  Fused conv implementation does not support grouped convolutions for now.
     [[node sequential/conv2d/Relu (defined at <ipython-input-9-36d4624b896d>:1) ]] [Op:__inference_train_function_1358]

Function call stack:
train_function`

(I am running on CPU)
I would be grateful for any kind of help that will solve this issue. Thank you.

**Comment by EscVM** [comment]
Hi @MFalam, 

That issue has been already covered in previous issues ----> #1 #8 #13
