### ISSUE TITLE
Can the model be used for NLP tasks

### ISSUE THREAD

**Issue by horacioHao** [EscVM/Efficient-CapsNet#15]
Can the model be used for NLP tasks

**Comment by EscVM** [comment]
Hi @horacioHao!

I think it could be an idea worth trying. Some recent studies point in the direction that reference frames are also important for natural language and reasoning. So, why don't give it a shot :)

![Alt Text](https://thumbs.gfycat.com/FocusedSlushyGuineafowl-max-1mb.gif)
