### ISSUE TITLE
performance problems

### ISSUE THREAD

**Issue by StephenTaylor1998** [EscVM/Efficient-CapsNet#3]
Is there a problem with the code?
The performance of the model may be abnormal.
There may be some problems with the accuracy.

Epoch 35/150
3750/3750 [==============================] - 142s 38ms/step - loss: 0.0191 - Original_CapsNet_loss: 0.0106 - Generator_loss: 0.0217 - Original_CapsNet_multiAccuracy: 0.5635 - val_loss: 0.0138 - val_Original_CapsNet_loss: 0.0056 - val_Generator_loss: 0.0209 - val_Original_CapsNet_multiAccuracy: 0.5458
Epoch 36/150
3750/3750 [==============================] - 141s 38ms/step - loss: 0.0184 - Original_CapsNet_loss: 0.0100 - Generator_loss: 0.0215 - Original_CapsNet_multiAccuracy: 0.5591 - val_loss: 0.0133 - val_Original_CapsNet_loss: 0.0051 - val_Generator_loss: 0.0209 - val_Original_CapsNet_multiAccuracy: 0.5900
Epoch 37/150
3750/3750 [==============================] - 142s 38ms/step - loss: 0.0181 - Original_CapsNet_loss: 0.0098 - Generator_loss: 0.0212 - Original_CapsNet_multiAccuracy: 0.5619 - val_loss: 0.0132 - val_Original_CapsNet_loss: 0.0052 - val_Generator_loss: 0.0204 - val_Original_CapsNet_multiAccuracy: 0.5344

**Comment by fsalv** [comment]
Hi. We actually found an error in the code that caused the usage of multiAccuracy, that is specifically conceived for the MultiMNIST dataset, with the original CapsNet on MNIST. This should be fixed now.
Thanks!
