### ISSUE TITLE
how to use it for other datasets?

### ISSUE THREAD

**Issue by flydragon2018** [EscVM/Efficient-CapsNet#5]
just build the dataset in some format?

or need to rewrite the graph?

**Comment by EscVM** [comment]
Hi @flydragon2018,

you could simply write a version of the network and fit it on your dataset.
Check [here](https://github.com/EscVM/Efficient-CapsNet/blob/main/models/efficient_capsnet_graph_mnist.py) the code on how to make a graph for MNIST.
