### ISSUE TITLE
how can I use my dataset to train this model ?

### ISSUE THREAD

**Issue by return-sleep** [EscVM/Efficient-CapsNet#7]
my image size is 64*64*3

**Comment by return-sleep** [comment]
AttributeError: 'tuple' object has no attribute 'shape'

**Comment by EscVM** [comment]
Hi @return-sleep!

Sorry for the delay in the reply.

So, the code was primarily structured to give reproducibility to the experimentation of our research. However, with some simple steps, you can adapt it for your dataset.

First of all, you need to create a model file like [this one](https://github.com/EscVM/Efficient-CapsNet/blob/main/models/efficient_capsnet_graph_mnist.py). Then, you have to modify [model script](https://github.com/EscVM/Efficient-CapsNet/blob/main/models/model.py), adding to the "load_graph" method of the EfficientCapsNet class your model.  Finally, create an object of the EfficientCapsNet and call the "train" method passing a dataset object with a method "get_tf_data" that provides a tf.data object for the training and one for validation. That's it.

Tell me if you want more information.
