### ISSUE TITLE
Overfitting

### ISSUE THREAD

**Issue by whongfeiHK** [EscVM/Efficient-CapsNet#9]
It is always overfitting on my own dataset, even I try my best to simplify the model which only contains 2000+ parameters. 
I data is (300*300*1) pictures, 800+ trainsing samples.
Anyone can guide me this? Thanks

**Comment by EscVM** [comment]
Hi @whongfeiHK!

If I understood correctly, your images are 300 x 300 with one channel, is it correct?

Are you using any regularization techniques?
